package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/terminator791/Layered-Architecture-graphql-GO/internal/domain/models"
	"github.com/terminator791/Layered-Architecture-graphql-GO/internal/presentation/graphql/generated"
)

// Basic resolver implementations for key functionality

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input models.CreateUserInput) (*models.AuthPayload, error) {
	return r.UserService.Register(ctx, &input)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input models.LoginInput) (*models.AuthPayload, error) {
	return r.UserService.Login(ctx, &input)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input models.CreateMessageInput) (*models.Message, error) {
	return r.MessageService.CreateMessage(ctx, &input)
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, room string) ([]*models.Message, error) {
	return r.MessageService.GetMessagesByRoom(ctx, room)
}

// MessageAdded is the resolver for the messageAdded field.
func (r *subscriptionResolver) MessageAdded(ctx context.Context, room string) (<-chan *models.Message, error) {
	return r.MessageService.SubscribeToRoom(ctx, room)
}

// Placeholder implementations for other mutations - will implement as needed
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	return true, nil
}

func (r *mutationResolver) UpdateUser(ctx context.Context, input models.UpdateUserInput) (*models.User, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.UserService.UpdateUser(ctx, userID, &input)
}

func (r *mutationResolver) UpdateUserStatus(ctx context.Context, status models.UserStatus) (*models.User, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.UserService.UpdateUserStatus(ctx, userID, status)
}

func (r *mutationResolver) DeleteUser(ctx context.Context) (bool, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	return true, r.UserService.DeleteUser(ctx, userID)
}

func (r *mutationResolver) CreateRoom(ctx context.Context, input models.CreateRoomInput) (*models.Room, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.RoomService.CreateRoom(ctx, userID, &input)
}

func (r *mutationResolver) UpdateRoom(ctx context.Context, roomID string, input models.UpdateRoomInput) (*models.Room, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.RoomService.UpdateRoom(ctx, userID, roomID, &input)
}

func (r *mutationResolver) DeleteRoom(ctx context.Context, roomID string) (bool, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	return true, r.RoomService.DeleteRoom(ctx, userID, roomID)
}

func (r *mutationResolver) JoinRoom(ctx context.Context, input models.JoinRoomInput) (*models.RoomMember, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.RoomService.JoinRoom(ctx, userID, &input)
}

func (r *mutationResolver) LeaveRoom(ctx context.Context, roomID string) (bool, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	return true, r.RoomService.LeaveRoom(ctx, userID, roomID)
}

func (r *mutationResolver) UpdateRoomMember(ctx context.Context, input models.UpdateRoomMemberInput) (*models.RoomMember, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.RoomService.UpdateRoomMember(ctx, userID, &input)
}

func (r *mutationResolver) KickRoomMember(ctx context.Context, roomID string, userID string) (bool, error) {
	currentUserID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	return true, r.RoomService.KickRoomMember(ctx, currentUserID, roomID, userID)
}

func (r *mutationResolver) SendMessageToRoom(ctx context.Context, roomID string, text string, messageType *models.MessageType, replyToID *string, metadata *generated.MessageMetadataInput) (*models.Message, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	// Convert metadata if provided
	var msgMetadata *models.MessageMetadata
	if metadata != nil {
		msgMetadata = &models.MessageMetadata{
			ImageWidth:  metadata.ImageWidth,
			ImageHeight: metadata.ImageHeight,
			ImageURL:    metadata.ImageURL,
			FileName:    metadata.FileName,
			FileURL:     metadata.FileURL,
			MimeType:    metadata.MimeType,
			SystemType:  metadata.SystemType,
		}
		if metadata.FileSize != nil {
			fileSize := int64(*metadata.FileSize)
			msgMetadata.FileSize = &fileSize
		}
	}

	return r.MessageService.SendMessageToRoom(ctx, userID, roomID, text, messageType, replyToID, msgMetadata)
}

func (r *mutationResolver) UpdateMessage(ctx context.Context, input models.UpdateMessageInput) (*models.Message, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.MessageService.UpdateMessage(ctx, userID, input.MessageID, &input)
}

func (r *mutationResolver) DeleteMessage(ctx context.Context, messageID string) (bool, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	return true, r.MessageService.DeleteMessage(ctx, userID, messageID)
}

func (r *mutationResolver) AddReaction(ctx context.Context, input models.AddReactionInput) (*models.MessageReaction, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.MessageService.AddReaction(ctx, userID, &input)
}

func (r *mutationResolver) RemoveReaction(ctx context.Context, input models.RemoveReactionInput) (bool, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	return true, r.MessageService.RemoveReaction(ctx, userID, &input)
}

func (r *mutationResolver) StartTyping(ctx context.Context, input models.StartTypingInput) (bool, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	return true, r.MessageService.StartTyping(ctx, userID, &input)
}

func (r *mutationResolver) StopTyping(ctx context.Context, input models.StopTypingInput) (bool, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	return true, r.MessageService.StopTyping(ctx, userID, &input)
}

// Placeholder query implementations
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.UserService.GetCurrentUser(ctx, userID)
}

func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	return r.UserService.GetUserByID(ctx, id)
}

func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int) ([]*models.User, error) {
	lim := 20
	off := 0
	if limit != nil {
		lim = *limit
	}
	if offset != nil {
		off = *offset
	}
	return r.UserService.ListUsers(ctx, lim, off)
}

func (r *queryResolver) Room(ctx context.Context, id string) (*models.Room, error) {
	return r.RoomService.GetRoomByID(ctx, id)
}

func (r *queryResolver) Rooms(ctx context.Context, limit *int, offset *int) ([]*models.Room, error) {
	lim := 20
	off := 0
	if limit != nil {
		lim = *limit
	}
	if offset != nil {
		off = *offset
	}
	return r.RoomService.ListRooms(ctx, lim, off)
}

func (r *queryResolver) MyRooms(ctx context.Context) ([]*models.Room, error) {
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.RoomService.GetUserRooms(ctx, userID)
}

func (r *queryResolver) MessagesByRoom(ctx context.Context, roomID string, limit *int, offset *int) ([]*models.Message, error) {
	lim := 50
	off := 0
	if limit != nil {
		lim = *limit
	}
	if offset != nil {
		off = *offset
	}
	return r.MessageService.GetMessagesByRoomID(ctx, roomID, lim, off)
}

func (r *queryResolver) Message(ctx context.Context, id string) (*models.Message, error) {
	return r.MessageService.GetMessageByID(ctx, id)
}

func (r *queryResolver) SearchMessages(ctx context.Context, query string, roomID *string, limit *int, offset *int) ([]*models.Message, error) {
	lim := 20
	off := 0
	if limit != nil {
		lim = *limit
	}
	if offset != nil {
		off = *offset
	}
	return r.MessageService.SearchMessages(ctx, query, roomID, lim, off)
}

// Placeholder subscription implementations
func (r *subscriptionResolver) MessageAddedToRoom(ctx context.Context, roomID string) (<-chan *models.Message, error) {
	return r.MessageService.SubscribeToRoomMessages(ctx, roomID)
}

func (r *subscriptionResolver) MessageUpdated(ctx context.Context, roomID string) (<-chan *models.Message, error) {
	// For now, use the same channel as message added
	// In a real implementation, you might want separate channels for different events
	return r.MessageService.SubscribeToRoomMessages(ctx, roomID)
}

func (r *subscriptionResolver) MessageDeleted(ctx context.Context, roomID string) (<-chan *models.Message, error) {
	// For now, use the same channel as message added
	return r.MessageService.SubscribeToRoomMessages(ctx, roomID)
}

func (r *subscriptionResolver) ReactionAdded(ctx context.Context, roomID string) (<-chan *models.MessageReaction, error) {
	return r.MessageService.SubscribeToRoomReactions(ctx, roomID)
}

func (r *subscriptionResolver) ReactionRemoved(ctx context.Context, roomID string) (<-chan *models.MessageReaction, error) {
	// For now, use the same channel as reaction added
	return r.MessageService.SubscribeToRoomReactions(ctx, roomID)
}

func (r *subscriptionResolver) UserStatusChanged(ctx context.Context, roomID string) (<-chan *models.User, error) {
	// This would require additional Redis channels for user status
	// For now, return a simple channel
	userCh := make(chan *models.User)
	close(userCh)
	return userCh, nil
}

func (r *subscriptionResolver) TypingStarted(ctx context.Context, roomID string) (<-chan *models.TypingIndicator, error) {
	// This would require additional Redis channels for typing indicators
	// For now, return a simple channel
	typingCh := make(chan *models.TypingIndicator)
	close(typingCh)
	return typingCh, nil
}

func (r *subscriptionResolver) TypingStopped(ctx context.Context, roomID string) (<-chan *models.TypingIndicator, error) {
	// This would require additional Redis channels for typing indicators
	// For now, return a simple channel
	typingCh := make(chan *models.TypingIndicator)
	close(typingCh)
	return typingCh, nil
}

func (r *subscriptionResolver) RoomMemberJoined(ctx context.Context, roomID string) (<-chan *models.RoomMember, error) {
	// This would require additional Redis channels for room events
	// For now, return a simple channel
	memberCh := make(chan *models.RoomMember)
	close(memberCh)
	return memberCh, nil
}

func (r *subscriptionResolver) RoomMemberLeft(ctx context.Context, roomID string) (<-chan *models.RoomMember, error) {
	// This would require additional Redis channels for room events
	// For now, return a simple channel
	memberCh := make(chan *models.RoomMember)
	close(memberCh)
	return memberCh, nil
}

func (r *subscriptionResolver) RoomMemberUpdated(ctx context.Context, roomID string) (<-chan *models.RoomMember, error) {
	// This would require additional Redis channels for room events
	// For now, return a simple channel
	memberCh := make(chan *models.RoomMember)
	close(memberCh)
	return memberCh, nil
}

func (r *subscriptionResolver) RoomUpdated(ctx context.Context, roomID string) (<-chan *models.Room, error) {
	// This would require additional Redis channels for room events
	// For now, return a simple channel
	roomCh := make(chan *models.Room)
	close(roomCh)
	return roomCh, nil
}

// Message field resolvers
func (r *messageResolver) ReactionCount(ctx context.Context, obj *models.Message) ([]*generated.ReactionCount, error) {
	if obj.ReactionCount == nil {
		return []*generated.ReactionCount{}, nil
	}

	var result []*generated.ReactionCount
	for emoji, count := range obj.ReactionCount {
		result = append(result, &generated.ReactionCount{
			Emoji: emoji,
			Count: count,
		})
	}

	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// Message returns generated.MessageResolver implementation.
func (r *Resolver) Message() generated.MessageResolver { return &messageResolver{r} }

// SendMessageInput returns generated.SendMessageInputResolver implementation.
func (r *Resolver) SendMessageInput() generated.SendMessageInputResolver { return &sendMessageInputResolver{r} }

// UpdateMessageInput returns generated.UpdateMessageInputResolver implementation.
func (r *Resolver) UpdateMessageInput() generated.UpdateMessageInputResolver { return &updateMessageInputResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type messageResolver struct{ *Resolver }
type sendMessageInputResolver struct{ *Resolver }
type updateMessageInputResolver struct{ *Resolver }

// Input resolvers for metadata handling
func (r *sendMessageInputResolver) Metadata(ctx context.Context, obj *models.CreateMessageInput, data *generated.MessageMetadataInput) error {
	if data == nil {
		return nil
	}

	metadata := &models.MessageMetadata{
		ImageWidth:  data.ImageWidth,
		ImageHeight: data.ImageHeight,
		ImageURL:    data.ImageURL,
		FileName:    data.FileName,
		FileURL:     data.FileURL,
		MimeType:    data.MimeType,
		SystemType:  data.SystemType,
	}

	// Convert int to int64 for FileSize
	if data.FileSize != nil {
		fileSize := int64(*data.FileSize)
		metadata.FileSize = &fileSize
	}

	obj.Metadata = metadata
	return nil
}

func (r *updateMessageInputResolver) Metadata(ctx context.Context, obj *models.UpdateMessageInput, data *generated.MessageMetadataInput) error {
	if data == nil {
		return nil
	}

	metadata := &models.MessageMetadata{
		ImageWidth:  data.ImageWidth,
		ImageHeight: data.ImageHeight,
		ImageURL:    data.ImageURL,
		FileName:    data.FileName,
		FileURL:     data.FileURL,
		MimeType:    data.MimeType,
		SystemType:  data.SystemType,
	}

	// Convert int to int64 for FileSize
	if data.FileSize != nil {
		fileSize := int64(*data.FileSize)
		metadata.FileSize = &fileSize
	}

	obj.Metadata = metadata
	return nil
}